services:
  - type: web
    name: helperbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: helperbot
          property: host
