services:
  - type: web
    name: helperbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "7206608966:AAFm0bwzbimunNiWTe7N-RwpVAlTsHU490E"
      - key: PORT
        value: "5000"
    plan: free
    branch: main
    autoDeploy: true
    repo: https://github.com/abdulloh012d/helperbot
